In [ ]:
import yfinance as yf
import numpy as np
import pandas as pd
import statsmodels.api as sm

# Análisis fundamental.

## Extracción de la información contable y financiera

Yahoo finance por permite acceder a toda la información que tiene publicada en su página web sobre una empresa. Pero el acceso a se realizad en a la **programación orientada a objetos (POO)**

`empresa = yf.Ticker(""ITX.MC"")``

`yf.Ticker` es una clase que es como un plantilla y `empresa` es una **instancia y objeto** de esa clase, es decir, un caso concreto creado con la plantilla.

In [ ]:
empresa = yf.Ticker("ITX.MC")
empresa

yfinance.Ticker object <ITX.MC>

`empresa` no es simplemente una variable que contiene un número o una lista. Es un objeto bastante más complejo que contiene:

- Datos y atributos
- Funciones asociadas al propio objeto que denominamos métodos

In [ ]:
print(type(empresa))

<class 'yfinance.ticker.Ticker'>

In [ ]:
dir(empresa)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_analysis',
 '_data',
 '_download_options',
 '_earnings',
 '_earnings_dates',
 '_expirations',
 '_fast_info',
 '_fetch_ticker_tz',
 '_financials',
 '_fundamentals',
 '_funds_data',
 '_get_earnings_dates_using_scrape',
 '_get_earnings_dates_using_screener',
 '_get_ticker_tz',
 '_holders',
 '_isin',
 '_lazy_load_price_history',
 '_message_handler',
 '_news',
 '_options2df',
 '_price_history',
 '_quote',
 '_shares',
 '_tz',
 '_underlying',
 'actions',
 'analyst_price_targets',
 'balance_sheet',
 'balancesheet',
 'calendar',
 'capital_gains',
 'cash_flow',
 'cashflow',
 'dividends',
 'earnings',
 'earnings_dates',
 'earnings_estimate',
 'earnings_history',
 'eps_revisions',
 'eps_trend',
 'fast_info',
 'financials',
 'funds_data',
 'get_actions',
 'get_analyst_price_targets',
 'get_balance_sheet',
 'get_balancesheet',
 'get_calendar',
 'get_capital_gains',
 'get_cash_flow',
 'get_cashflow',
 'get_dividends',
 'get_earnings',
 'get_earnings_dates',
 'get_earnings_estimate',
 'get_earnings_history',
 'get_eps_revisions',
 'get_eps_trend',
 'get_fast_info',
 'get_financials',
 'get_funds_data',
 'get_growth_estimates',
 'get_history_metadata',
 'get_income_stmt',
 'get_incomestmt',
 'get_info',
 'get_insider_purchases',
 'get_insider_roster_holders',
 'get_insider_transactions',
 'get_institutional_holders',
 'get_isin',
 'get_major_holders',
 'get_mutualfund_holders',
 'get_news',
 'get_recommendations',
 'get_recommendations_summary',
 'get_revenue_estimate',
 'get_sec_filings',
 'get_shares',
 'get_shares_full',
 'get_splits',
 'get_sustainability',
 'get_upgrades_downgrades',
 'growth_estimates',
 'history',
 'history_metadata',
 'income_stmt',
 'incomestmt',
 'info',
 'insider_purchases',
 'insider_roster_holders',
 'insider_transactions',
 'institutional_holders',
 'isin',
 'live',
 'major_holders',
 'mutualfund_holders',
 'news',
 'option_chain',
 'options',
 'quarterly_balance_sheet',
 'quarterly_balancesheet',
 'quarterly_cash_flow',
 'quarterly_cashflow',
 'quarterly_earnings',
 'quarterly_financials',
 'quarterly_income_stmt',
 'quarterly_incomestmt',
 'recommendations',
 'recommendations_summary',
 'revenue_estimate',
 'sec_filings',
 'session',
 'shares',
 'splits',
 'sustainability',
 'ticker',
 'ttm_cash_flow',
 'ttm_cashflow',
 'ttm_financials',
 'ttm_income_stmt',
 'ttm_incomestmt',
 'upgrades_downgrades',
 'ws']

## CUENTA DE RESULTADOS

In [ ]:
resultados=empresa.income_stmt
resultados

,2026-01-31,2025-01-31,2024-01-31,2023-01-31
Tax Effect Of Unusual Items,-1.503741e+07,-2.669922e+07,-2.254367e+07,-8.498246e+07
Tax Rate For Calcs,2.244390e-01,2.243630e-01,2.147020e-01,2.260170e-01
Normalized EBITDA,1.161200e+10,1.106500e+10,1.014300e+10,8.654000e+09
Total Unusual Items,-6.700000e+07,-1.190000e+08,-1.050000e+08,-3.760000e+08
Total Unusual Items Excluding Goodwill,-6.700000e+07,-1.190000e+08,-1.050000e+08,-3.760000e+08
Net Income From Continuing Operation Net Minority Interest,6.220000e+09,5.866000e+09,5.381000e+09,4.130000e+09
Reconciled Depreciation,3.141000e+09,2.997000e+09,2.897000e+09,2.776000e+09
Reconciled Cost Of Revenue,1.664200e+10,1.628800e+10,1.518600e+10,1.401100e+10
EBITDA,1.154500e+10,1.094600e+10,1.003800e+10,8.278000e+09
EBIT,8.390000e+09,7.930000e+09,7.141000e+09,5.502000e+09
Net Interest Income,-3.100000e+07,8.900000e+07,1.090000e+08,-5.900000e+07
Interest Expense,3.700000e+08,3.530000e+08,2.710000e+08,1.440000e+08
Interest Income,3.390000e+08,4.420000e+08,3.800000e+08,8.500000e+07
Normalized Income,6.271963e+09,5.958301e+09,5.463456e+09,4.421018e+09
Net Income From Continuing And Discontinued Operation,6.220000e+09,5.866000e+09,5.381000e+09,4.130000e+09
Total Expenses,3.180000e+10,3.095800e+10,2.903400e+10,2.667500e+10
Rent Expense Supplemental,1.085000e+09,1.072000e+09,9.890000e+08,8.590000e+08
Total Operating Income As Reported,7.997000e+09,7.554000e+09,6.809000e+09,5.520000e+09
Diluted Average Shares,3.117794e+09,3.118554e+09,3.117613e+09,3.114630e+09
Basic Average Shares,3.116091e+09,3.114453e+09,3.112837e+09,3.112455e+09
Diluted EPS,1.995000e+00,1.881000e+00,1.726000e+00,1.326000e+00
Basic EPS,1.996000e+00,1.884000e+00,1.729000e+00,1.327000e+00
Diluted NI Availto Com Stockholders,6.220000e+09,5.866000e+09,5.381000e+09,4.130000e+09
Net Income Common Stockholders,6.220000e+09,5.866000e+09,5.381000e+09,4.130000e+09
Otherunder Preferred Stock Dividend,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Net Income,6.220000e+09,5.866000e+09,5.381000e+09,4.130000e+09
Minority Interests,0.000000e+00,-1.100000e+07,-1.400000e+07,-1.700000e+07
Net Income Including Noncontrolling Interests,6.220000e+09,5.877000e+09,5.395000e+09,4.147000e+09
Net Income Continuous Operations,6.220000e+09,5.877000e+09,5.395000e+09,4.147000e+09
Tax Provision,1.800000e+09,1.700000e+09,1.475000e+09,1.211000e+09
Pretax Income,8.020000e+09,7.577000e+09,6.870000e+09,5.358000e+09
Other Non Operating Income Expenses,NaN,NaN,NaN,-2.310000e+08
Special Income Charges,-6.700000e+07,-1.190000e+08,-1.050000e+08,-3.760000e+08
Other Special Charges,6.700000e+07,1.190000e+08,1.050000e+08,3.760000e+08
Impairment Of Capital Assets,4.769900e+07,3.909400e+07,4.748000e+07,NaN
Net Non Operating Interest Income Expense,-3.100000e+07,8.900000e+07,1.090000e+08,-5.900000e+07
Interest Expense Non Operating,3.700000e+08,3.530000e+08,2.710000e+08,1.440000e+08
Interest Income Non Operating,3.390000e+08,4.420000e+08,3.800000e+08,8.500000e+07
Operating Income,8.064000e+09,7.673000e+09,6.914000e+09,5.895000e+09
Operating Expense,1.515800e+10,1.467000e+10,1.384800e+10,1.266400e+10
Other Operating Expenses,1.413000e+09,1.227000e+09,1.246000e+09,1.246000e+09
Depreciation And Amortization In Income Statement,3.155000e+09,3.016000e+09,2.888000e+09,2.701000e+09
Amortization,3.155000e+09,3.016000e+09,2.888000e+09,2.701000e+09
Depreciation Income Statement,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Selling General And Administration,3.591000e+09,3.712000e+09,3.368000e+09,3.105000e+09
Selling And Marketing Expense,3.028000e+09,3.031000e+09,2.733000e+09,2.546000e+09
General And Administrative Expense,5.630000e+08,6.810000e+08,6.350000e+08,5.590000e+08
Rent And Landing Fees,1.085000e+09,1.072000e+09,9.890000e+08,8.590000e+08
Gross Profit,2.322200e+10,2.234300e+10,2.076200e+10,1.855900e+10
Cost Of Revenue,1.664200e+10,1.628800e+10,1.518600e+10,1.401100e+10
Total Revenue,3.986400e+10,3.863200e+10,3.594700e+10,3.256900e+10
Operating Revenue,3.986400e+10,3.863200e+10,3.594700e+10,3.256900e+10

In [ ]:
type(empresa.income_stmt)

pandas.core.frame.DataFrame

In [ ]:
resultados.index

Index(['Tax Effect Of Unusual Items', 'Tax Rate For Calcs',
       'Normalized EBITDA', 'Total Unusual Items',
       'Total Unusual Items Excluding Goodwill',
       'Net Income From Continuing Operation Net Minority Interest',
       'Reconciled Depreciation', 'Reconciled Cost Of Revenue', 'EBITDA',
       'EBIT', 'Net Interest Income', 'Interest Expense', 'Interest Income',
       'Normalized Income',
       'Net Income From Continuing And Discontinued Operation',
       'Total Expenses', 'Rent Expense Supplemental',
       'Total Operating Income As Reported', 'Diluted Average Shares',
       'Basic Average Shares', 'Diluted EPS', 'Basic EPS',
       'Diluted NI Availto Com Stockholders', 'Net Income Common Stockholders',
       'Otherunder Preferred Stock Dividend', 'Net Income',
       'Minority Interests', 'Net Income Including Noncontrolling Interests',
       'Net Income Continuous Operations', 'Tax Provision', 'Pretax Income',
       'Other Non Operating Income Expenses', 'Special Income Charges',
       'Other Special Charges', 'Impairment Of Capital Assets',
       'Net Non Operating Interest Income Expense',
       'Interest Expense Non Operating', 'Interest Income Non Operating',
       'Operating Income', 'Operating Expense', 'Other Operating Expenses',
       'Depreciation And Amortization In Income Statement', 'Amortization',
       'Depreciation Income Statement', 'Selling General And Administration',
       'Selling And Marketing Expense', 'General And Administrative Expense',
       'Rent And Landing Fees', 'Gross Profit', 'Cost Of Revenue',
       'Total Revenue', 'Operating Revenue'],
      dtype='object')

In [ ]:
orden = [
    "Total Revenue",
    "Cost Of Revenue",
    "Gross Profit",
    "Operating Expense",
    "Operating Income",
    "Interest Expense",
    "Pretax Income",
    "Tax Provision",
    "Net Income"
]

Voy a crear una list comprehension que es una nueva lista que voy a llamar `orden_disponible` en el que guardaremos únicamente las partidas de la lista `orden` que está disponible en `resultados.index`

In [ ]:
orden_disponible = [
    partida for partida in orden
    if partida in resultados.index
]
resultados= resultados.loc[orden_disponible] # seleccionamos las filas que necesitamos.
resultados

                     2026-01-31    2025-01-31    2024-01-31    2023-01-31
Total Revenue      3.986400e+10  3.863200e+10  3.594700e+10  3.256900e+10
Cost Of Revenue    1.664200e+10  1.628800e+10  1.518600e+10  1.401100e+10
Gross Profit       2.322200e+10  2.234300e+10  2.076200e+10  1.855900e+10
Operating Expense  1.515800e+10  1.467000e+10  1.384800e+10  1.266400e+10
Operating Income   8.064000e+09  7.673000e+09  6.914000e+09  5.895000e+09
Interest Expense   3.700000e+08  3.530000e+08  2.710000e+08  1.440000e+08
Pretax Income      8.020000e+09  7.577000e+09  6.870000e+09  5.358000e+09
Tax Provision      1.800000e+09  1.700000e+09  1.475000e+09  1.211000e+09
Net Income         6.220000e+09  5.866000e+09  5.381000e+09  4.130000e+09

In [ ]:
# Utilizamos un diccionario para proceder a la traducción de las partidas contables
traduccion = {
    "Total Revenue": "Ingresos",
    "Cost Of Revenue": "Coste de ventas",
    "Gross Profit": "Margen bruto",
    "Operating Expense": "Gastos operativos",
    "Operating Income": "Resultado operativo",
    "Interest Expense": "Gastos financieros",
    "Pretax Income": "Resultado antes de impuestos",
    "Tax Provision": "Impuestos",
    "Net Income": "Beneficio neto"
}

In [ ]:
resultados_es = resultados.rename(index=traduccion)
resultados_es

,2026-01-31,2025-01-31,2024-01-31,2023-01-31
Ingresos,3.986400e+10,3.863200e+10,3.594700e+10,3.256900e+10
Coste de ventas,1.664200e+10,1.628800e+10,1.518600e+10,1.401100e+10
Margen bruto,2.322200e+10,2.234300e+10,2.076200e+10,1.855900e+10
Gastos operativos,1.515800e+10,1.467000e+10,1.384800e+10,1.266400e+10
Resultado operativo,8.064000e+09,7.673000e+09,6.914000e+09,5.895000e+09
Gastos financieros,3.700000e+08,3.530000e+08,2.710000e+08,1.440000e+08
Resultado antes de impuestos,8.020000e+09,7.577000e+09,6.870000e+09,5.358000e+09
Impuestos,1.800000e+09,1.700000e+09,1.475000e+09,1.211000e+09
Beneficio neto,6.220000e+09,5.866000e+09,5.381000e+09,4.130000e+09

**EJERCICIO** extrae el balance con la siguient estructura y lo traduces al español

In [ ]:
orden_balance = [
    "Cash Cash Equivalents And Short Term Investments",
    "Accounts Receivable",
    "Inventory",
    "Current Assets",

    "Net PPE",
    "Goodwill And Other Intangible Assets",
    "Total Assets",

    "Current Liabilities",
    "Long Term Debt",
    "Total Liabilities Net Minority Interest",

    "Stockholders Equity"
]

In [ ]:
balance = empresa.balance_sheet
balance

,2026-01-31,2025-01-31,2024-01-31,2023-01-31,2022-01-31
Treasury Shares Number,2.852320e+05,1.905846e+06,3.582419e+06,4.932514e+06,NaN
Ordinary Shares Number,3.116367e+09,3.114746e+09,3.113070e+09,3.111719e+09,NaN
Share Issued,3.116652e+09,3.116652e+09,3.116652e+09,3.116652e+09,NaN
Total Debt,6.095000e+09,5.909000e+09,5.739000e+09,5.596000e+09,NaN
Tangible Book Value,1.855500e+10,1.806900e+10,1.722200e+10,1.600500e+10,NaN
...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,1.096000e+10,1.150200e+10,1.142200e+10,1.008300e+10,NaN
Other Short Term Investments,5.684000e+09,5.120000e+09,4.415000e+09,4.522000e+09,NaN
Cash And Cash Equivalents,5.276000e+09,6.382000e+09,7.007000e+09,5.561000e+09,NaN
Cash Equivalents,2.847000e+09,4.881000e+09,4.621000e+09,3.031000e+09,NaN
Cash Financial,2.429000e+09,1.501000e+09,2.386000e+09,2.530000e+09,NaN

**EJERCICIO** Extrae la informacion del flujo de caja con la siguiente estructura.

In [ ]:
orden_flujos = [
    "Net Income From Continuing Operations",
    "Depreciation And Amortization",
    "Change In Working Capital",
    "Operating Cash Flow",

    "Capital Expenditure",
    "Investing Cash Flow",

    "Issuance Of Debt",
    "Repayment Of Debt",
    "Repurchase Of Capital Stock",
    "Cash Dividends Paid",
    "Financing Cash Flow",

    "Changes In Cash"
]

In [ ]:
cashflow = empresa.cashflow
cashflow

,2026-01-31,2025-01-31,2024-01-31,2023-01-31,2022-01-31
Free Cash Flow,6.520000e+09,6.616000e+09,6.795000e+09,5.259000e+09,NaN
Repurchase Of Capital Stock,NaN,NaN,0.000000e+00,-6.100000e+07,-71000000.0
Repayment Of Debt,NaN,0.000000e+00,-1.000000e+06,-1.000000e+06,-5000000.0
Issuance Of Debt,NaN,NaN,4.000000e+06,NaN,NaN
Capital Expenditure,-2.712000e+09,-2.672000e+09,-1.872000e+09,-1.415000e+09,NaN
End Cash Position,5.276000e+09,6.382000e+09,7.007000e+09,5.561000e+09,NaN
Other Cash Adjustment Outside Changein Cash,NaN,NaN,-1.000000e+06,1.000000e+06,NaN
Beginning Cash Position,6.382000e+09,7.007000e+09,5.561000e+09,7.021000e+09,NaN
Effect Of Exchange Rate Changes,-4.800000e+07,-1.800000e+07,-3.800000e+07,-1.700000e+07,NaN
Changes In Cash,-1.058000e+09,-6.070000e+08,1.485000e+09,-1.444000e+09,NaN
Financing Cash Flow,-7.075000e+09,-6.607000e+09,-5.473000e+09,-4.614000e+09,NaN
Net Other Financing Charges,-1.000000e+06,-1.810057e+09,1.000000e+06,NaN,NaN
Cash Dividends Paid,-5.235000e+09,-4.797000e+09,-3.744000e+09,-2.914000e+09,NaN
Common Stock Dividend Paid,-5.235000e+09,-4.797000e+09,-3.744000e+09,-2.914000e+09,NaN
Net Common Stock Issuance,NaN,NaN,0.000000e+00,-6.100000e+07,-71000000.0
Common Stock Payments,NaN,NaN,0.000000e+00,-6.100000e+07,-71000000.0
Net Issuance Payments Of Debt,-5.000000e+06,-8.000000e+06,3.000000e+06,-1.800000e+07,NaN
Net Short Term Debt Issuance,-5.000000e+06,-8.000000e+06,4.000000e+06,-1.700000e+07,NaN
Short Term Debt Issuance,NaN,NaN,4.000000e+06,NaN,NaN
Net Long Term Debt Issuance,NaN,0.000000e+00,-1.000000e+06,-1.000000e+06,-5000000.0
Long Term Debt Payments,NaN,0.000000e+00,-1.000000e+06,-1.000000e+06,-5000000.0
Investing Cash Flow,-3.215000e+09,-3.288000e+09,-1.709000e+09,-3.504000e+09,NaN
Net Other Investing Changes,4.000000e+06,5.200000e+07,-5.000000e+06,3.500000e+07,NaN
Net Investment Purchase And Sale,-4.910000e+08,-6.540000e+08,1.680000e+08,-2.124000e+09,NaN
Sale Of Investment,6.000000e+07,5.500000e+07,1.850000e+08,2.700000e+07,NaN
Purchase Of Investment,-5.510000e+08,-7.090000e+08,-1.700000e+07,-2.151000e+09,NaN
Net Business Purchase And Sale,-1.600000e+07,-1.400000e+07,0.000000e+00,NaN,0.0
Purchase Of Business,-1.600000e+07,-1.400000e+07,0.000000e+00,NaN,0.0
Net Intangibles Purchase And Sale,-5.190000e+08,-4.650000e+08,-4.730000e+08,-3.880000e+08,NaN
Purchase Of Intangibles,-5.190000e+08,-4.650000e+08,-4.730000e+08,-3.880000e+08,NaN
Net PPE Purchase And Sale,-2.193000e+09,-2.207000e+09,-1.399000e+09,-1.027000e+09,NaN
Sale Of PPE,NaN,NaN,NaN,NaN,0.0
Purchase Of PPE,-2.193000e+09,-2.207000e+09,-1.399000e+09,-1.027000e+09,NaN
Operating Cash Flow,9.232000e+09,9.288000e+09,8.667000e+09,6.674000e+09,NaN
Taxes Refund Paid,-1.585000e+09,-1.539000e+09,-1.460000e+09,-1.176000e+09,NaN
Change In Working Capital,-8.030000e+08,-1.980000e+08,-5.600000e+07,-6.690000e+08,NaN
Change In Payable,-6.630000e+08,3.920000e+08,1.540000e+08,-4.180000e+08,NaN
Change In Inventory,9.000000e+06,-4.270000e+08,1.300000e+08,-1.930000e+08,NaN
Change In Receivables,-1.490000e+08,-1.640000e+08,-3.410000e+08,-5.800000e+07,NaN
Other Non Cash Items,4.330000e+08,3.530000e+08,3.120000e+08,2.860000e+08,NaN
Provisionand Write Offof Assets,4.800000e+07,3.900000e+07,4.800000e+07,5.300000e+07,NaN
Deferred Tax,NaN,NaN,NaN,NaN,-734000000.0
Depreciation And Amortization,3.141000e+09,2.997000e+09,2.897000e+09,2.776000e+09,NaN
Amortization Cash Flow,5.610000e+08,5.400000e+08,3.860000e+08,3.240000e+08,NaN
Depreciation,2.580000e+09,2.457000e+09,2.511000e+09,2.452000e+09,NaN
Gain Loss On Investment Securities,6.700000e+07,1.190000e+08,1.050000e+08,1.450000e+08,NaN
Net Foreign Currency Exchange Gain Loss,NaN,NaN,NaN,7.000000e+06,NaN
Net Income From Continuing Operations,8.020000e+09,7.577000e+09,6.870000e+09,5.358000e+09,NaN

# ANÁLISIS DE LA RENTABILIDAD

##Rentabilidad económica

$$ROA=\frac{EBIT}{Activo Total}=\frac{EBIT}{Ventas}\times\frac{Ventas}{Activo Total}$$

In [ ]:
tickers = [
    "ITX.MC",   # Inditex
    "ADS.DE",   # Adidas
    "MC.PA",    # LVMH
    "NKE",      # Nike
    "9983.T",   # Fast Retailing / Uniqlo
    "BOSS.DE"   # Hugo Boss
]

**EJERCICIO** Estima el margen, la rotacion y la rentabilidad economica (ROA) de las empresas. Calcula en primer lugar la de Inditex "ITX.MC"

**EJERCICIO** Ahora lo calculamos para el resto de empresas del sector para poder compararlas.

Descomponemos la rotación
$$\frac{Ventas}{\text{Activo Total}}=\left\{
\begin{array}{l}
\frac{Ventas}{\text{Activo Corriente}} \\
\frac{Ventas}{\text{Activo No Corriente}}\end{array}
\right.$$

# ROE

## Rentabilidad Financiera
$$ROE=\frac{\text{Beneficio Neto}}{Patrimonio}$$

## Apalancamiento Financiero

$$ROC=\frac{\text{Beneficio sin Intereses y Después de Impuestos}}{Activo Total}$$

$$ROE=ROC+\left(ROC-k_d(1-\tau)\times \frac{Deuda}{Patrimonio}\right)$$

$$k_d=\frac{Intereses}{Deuda}$$


$$\tau=\frac{Impuestos}{Beneficio Neto}$$

# RATIOS DE MERCADO

$$Price-to-book=\frac{\text{Capitalización Bursatil}}{\text{Patrimonio Neto}}$$


$$PER=\frac{Precio}{\text{Benefcio Neto}}$$

In [ ]:
empresa = yf.Ticker("ITX.MC")

price_to_book = empresa.info.get("priceToBook")
per = empresa.info.get("trailingPE")

print(price_to_book,per)

9.406838 26.174757

**EJERCICIO** Compara el PER y Price to Book entre todas la empresas

**EJERCICIO** Analiza si los fundamentales estimados tienen explican el comportamiento de la rentabilidad de las empresas analizadas durante el ultimo año.